const conditions = [
    "Cancer - Pain",
    "Cancer - Nausea",
    "Cancer - Wasting",
    "Glaucoma",
    "HIV/AIDS",
    "Seizures",
    "Muscle Spasms",
    "Autism",
    "Sleep Apnia",
    "Tourette Syndrome",
    "ALS",
    "IBS",
    "Intractable Pain",
    "PSD"
  ];
  
  const flavors = [
    "Earthy",
    "Sweet",
    "Citrus",
    "Flowery",
    "Violet",
    "Diesel",
    "Spicy/Herbal",
    "Sage",
    "Woody",
    "Apricot",
    "Grapefruit",
    "Orange",
    "None",
    "Pungent",
    "Grape",
    "Pine",
    "Skunk",
    "Berry",
    "Pepper",
    "Menthol",
    "Blue",
    "Cheese",
    "Chemical",
    "Mango",
    "Lemon",
    "Peach",
    "Vanilla",
    "Nutty",
    "Chestnut",
    "Tea",
    "Tobacco",
    "Tropical",
    "Strawberry",
    "Blueberry",
    "Mint",
    "Apple",
    "Honey",
    "Lavender",
    "Lime",
    "Coffee",
    "Ammonia",
    "Minty",
    "Tree",
    "Fruit",
    "Butter",
    "Pineapple",
    "Tar",
    "Rose",
    "Plum",
    "Pear"
  ];
  
  const effects = [
    "Creative",
    "Energetic",
    "Tingly",
    "Euphoric",
    "Relaxed",
    "Aroused",
    "Happy",
    "Uplifted",
    "Hungry",
    "Talkative",
    "None",
    "Giggly",
    "Focused",
    "Sleepy",
    "Dry Mouth"
  ];